# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 1.5         #0.5
  joint_a2: 0.9         #-0.7854
  joint_a3: 0.0
  joint_a4: 1.7         #1.3962
  joint_a5: 0.0
  joint_a6: -1.3        #0.6109
  joint_a7: 0.0
